### ISSUE TITLE
Doesn't run/missing file

### ISSUE THREAD

**Issue by notSeaSmoke** [Inpacchi/Manga-Tagger#2]
The run.bat is calling a 'MangaTagger.py' which isn't present in the source. Don't see any install.bat either to install it with NSSM.

**Comment by Inpacchi** [comment]
Ah, I don't know how I missed some files not being uploaded when I committed the initial code.

**Comment by Inpacchi** [comment]
Fixed with commit 5db192fb06769e9acf5f9530172ba2844e2fa036
